# These are supported funding model platforms for DevForge

# GitHub Sponsors (recommended)
# github: [arghya29]

# Open Collective
# open_collective: devforge

# Ko-fi
# ko_fi: arghya29

# IssueHunt
# issuehunt: arghya29

# Custom
# custom: ["https://buymeacoffee.com/arghya29"]
